### PR TITLE
Fixed version description in filename

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
Any suggestions?  What can I do about the build timing out?

**Comment by Lnaden** [comment]
The OSX builds time out because its trying to build for 4 versions of python (2.7, 3.5, 3.6, and 3.7) in each of the builds. The Brew update and other OSX startup things consume a fair chunk of boot time, and so they ultimately time out. I don't see any particular errors in the builds I looked at beyond time out, so it could be that merging this will cause the builds to start uploading as they complete and we just have to re-trigger them a few times. I believe @jchodera has had to do that the past couple releases. 

It would be possible to split the builds even further where each Travis build does only 1 cuda and 1 python, but then you would be waiting for concurrency and paying the startup overhead costs on each of thm.

**Comment by peastman** [comment]
Ok, I'll try that then.  Thanks!

**Comment by peastman** [comment]
It's completed 18 of the 28 Mac packages, but retriggering the builds doesn't seem to help.  It just times out again without uploading anything further.  @jchodera?

**Comment by peastman** [comment]
It appears to have completed all the builds for Python 3.5, 3.6, and 3.7, but none of the ones for 2.7.  Would it make sense to do a new PR that disables building all the other versions so it can go straight to 2.7?

**Comment by jchodera** [comment]
For future reference: We usually have to manually retrigger builds once or twice due to timeouts on the `osx` builds.

**Comment by peastman** [comment]
I did manually retrigger them, but it didn't help.  It still timed out at the same point.  Instead I had to reverse the order of the builds so the 2.7 builds would get done first instead of last.

**Pull request merged**
