### PR TITLE
Build OpenMM 7.3.1 release candidate

### PR DESCRIPTION
**Pull request by peastman**
@jchodera can you check that all of this looks correct?

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good! We've been having issues with the `conda-build` compiler toolchain again (sigh) so we may need to do some debugging to get this built.

Have been buried in grantwriting this week...apologies for the slow response.

**Comment by peastman** [comment]
A bunch of the builds are failing.  For the Mac builds, it looks like it's because the script invokes `brew -y`, and there's no such option as `-y`.  For the Windows builds it has the error message

```
Error: bad character '"' in build/string: py37_cuda"100"_rc_1
```

**Comment by jchodera** [comment]
>  For the Mac builds, it looks like it's because the script invokes `brew -y`, and there's no such option as `-y`

They keep changing the syntax. We've fixed that elsewhere, but not here. Can you implement [this fix](https://github.com/omnia-md/conda-recipes/commit/df38ae375874d550d0824cd552c51dc1a8aa0ffb) and get rid of the `-y` globally?

> For the Windows builds it has the error message

We can't build `conda` packages for `win` using this build machinery yet. I started to experiment with this in this PR, but never got very far:

https://github.com/omnia-md/conda-recipes-cuda/pull/2

**Comment by jchodera** [comment]
I did get pretty far in the AppVeyor overhaul in https://github.com/omnia-md/conda-recipes-cuda/pull/2, and installation of the CUDA 10.0 toolkit actually worked---but I think we're still building for CUDA 9.2, right?

**Comment by peastman** [comment]
Right.

**Comment by jchodera** [comment]
OK, this should push all the packages after a few tries.

**Pull request merged**
