### PR TITLE
Updated build number

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by jchodera** [comment]
Shoot, it's still skipping them. I'm not sure why, but my guess is that it has to do with the [custom build labels](https://github.com/omnia-md/conda-recipes-cuda/pull/9/files#diff-7844bc65941f15646bf4df7d3c673410R22).

Instead, can I close this PR, manually delete the `rc` build packages, and retrigger the `master` build to push the new builds?

**Comment by jchodera** [comment]
On second thought, that wouldn't force any deployed packages from the previous release candidate to be updated, so we should probably get this PR to actually work.

Can you try changing the [`string`](https://github.com/omnia-md/conda-recipes-cuda/pull/9/files#diff-7844bc65941f15646bf4df7d3c673410R22) too?

**Comment by jchodera** [comment]
I think the `string` should end with the build number, so I'd go to `number: 2` and change the trailing `_1` to `_2`. Sorry about missing this earlier.

**Comment by peastman** [comment]
Are you sure it isn't working?  Don't I need to merge the PR before it will update them?

**Comment by jchodera** [comment]
> Are you sure it isn't working? Don't I need to merge the PR before it will update them?

No, it should still rebuild them if it thinks it is being asked to build something different from what is online already---it just can't upload them unless it is on `master`. It somehow thinks the versions on anaconda cloud are the same version as what it is being asked to build and skipping them as a result.

**Comment by jchodera** [comment]
That did the trick!

**Pull request merged**
