### PR TITLE
OpenMM 7.4.1 rc1

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
The Linux build is failing to start up:

```
Error response from daemon: manifest for jchodera/omnia-linux-anvil:texlive18-cuda not found
```

The Mac build gets further, but fails with the message

```
devtools/osx-build.sh: line 55: CUDA_VERSION: unbound variable
```

What's changed since we built 7.4.0?

**Comment by jchodera** [comment]
As usual, nothing I know of has changed, but everything is still broken. Every. Time.

**Comment by peastman** [comment]
Or as I frequently say: Nothing. Ever. Works.

It looks like both of these are symptoms of the same problem: for some reason the CUDA_VERSION and CUDA_SHORT_VERSION variables aren't set.  Those are part of the matrix defined in the travis file:

https://github.com/omnia-md/conda-recipes-cuda/blob/c09f80a2a01441b78db792ee279b780f6bd0adca/.travis.yml#L34-L42

I guess the first thing to do is just rerun it, in case travis was just having a bad day.  If it's still broken then further debugging will be needed.

**Comment by jchodera** [comment]
Aha! @j-wags recently ran into the same symptom! I seem to recall it was due to a recent change in Travis build matrix syntax?

**Comment by peastman** [comment]
Is it just that you don't include the `matrix:` line anymore?  The examples at https://docs.travis-ci.com/user/build-matrix/ don't include it.

**Comment by jchodera** [comment]
It's worth a try!

Also cc: https://github.com/omnia-md/conda-recipes/pull/996

**Comment by peastman** [comment]
Perfect, thanks.  I just made the changes and it looks like it's working now.

**Comment by jchodera** [comment]
We should also fix this in https://github.com/omnia-md/conda-dev-recipes

**Comment by peastman** [comment]
Builds are passing except that the Mac ones time out, as usual, so I'm going to merge this.

**Comment by jchodera** [comment]
We can just retrigger travis a few times.

**Comment by peastman** [comment]
I can also use the same trick as last time: let it run through as many builds as it has time for, then send a new PR to reverse the order of the builds.

**Comment by peastman** [comment]
> We can just retrigger travis a few times.

I tried, but it doesn't work.  It still repeats the full set of builds, so it just times out again without ever completing the last ones.  We need to switch the order to make it do those ones first.

**Comment by jchodera** [comment]
That's not right. It shouldn't rebuild packages that have already been pushed.

What channel are you pushing into? We must not have added that channel to the "check against these channels to see if the package exists" argument to conda-build-all.

**Comment by peastman** [comment]
> What channel are you pushing into?

omnia, of course.

**Comment by jchodera** [comment]
Sorry, I meant "what channel and label are you pushing to?"

**Comment by peastman** [comment]
It's using the various rccudaXX labels.

**Comment by jchodera** [comment]
The issue must be that we're not having `conda-build-all` check against all those labels so that it doesn't try to rebuild packages that are already there.

**Pull request merged**
