### PR TITLE
[openmm] 7.4.2 rc alternative build attempt

### PR DESCRIPTION
**Pull request by jchodera**
This is an alternative attempt to build OpenMM 7.4.2 rc from #23

### CODE REVIEW

**Comment by jaimergp** [comment]
Looks to me like the Miniconda installation fails silently in MacOS :/

**Comment by peastman** [comment]
You could also try `brew install miniconda`.

**Comment by jchodera** [comment]
> Looks to me like the Miniconda installation fails silently in MacOS :/

I can reproduce this locally! 
```bash
curl -s -O https://repo.continuum.io/miniconda/Miniconda3-4.6.14-MacOSX-x86_64.sh;
```
produces an empty file, which silently executes when run with `bash`!

Debugging now.

**Comment by Lnaden** [comment]
looks like this: https://github.com/MolSSI/cookiecutter-cms/issues/103

miniconda redirected the url but `curl -s` alone wont follow the redirect and fails

**Comment by jaimergp** [comment]
Oh, nice catch! `curl -sLO` should also work in that case?

**Pull request merged**
