### PR TITLE
Updated git revision for OpenMM 7.3.1

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
The new builds don't appear to have gotten pushed to conda.  Is there something else I need to do?

**Comment by jchodera** [comment]
They're there!
https://anaconda.org/omnia/openmm/files

They're in the `rc` and `rccudaXY` channels.

**Comment by peastman** [comment]
No, those are the old versions that got built two days ago.  I just updated the git revision last night, but they haven't gotten rebuilt.

**Comment by jchodera** [comment]
> No, those are the old versions that got built two days ago. I just updated the git revision last night, but they haven't gotten rebuilt.

Oh! I see [this PR](https://github.com/omnia-md/conda-recipes-cuda/pull/8/files).

For safety, these will not overwrite existing builds. You will have to increment the [build number](https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#build-number-and-string) in the recipe to force new packages to be built and pushed.

**Comment by peastman** [comment]
> Oh! I see this PR.

Yes, the PR you just posted a comment on. :)

**Comment by jchodera** [comment]
LOL. Until this grant is in Tue, please expect more temporary insanity.

**Pull request merged**
